flags:
  transformers-compat:
    five-three: true
packages:
- .
system-ghc: true
extra-deps:
- cereal-0.5.7.0
- exceptions-0.10.0
- mtl-2.2.2
- network-2.8.0.0
- network-simple-0.4.3
- safe-exceptions-0.1.7.0
- socks-0.5.6
- transformers-0.5.5.0
- transformers-compat-0.6.2
resolver: ghc-8.4.3